remote_theme: jekyll/minima

title: Ai Data Engineering
description: Adventures in Data Engineering
author:
  name: Graham Garnsworthy

header_pages:
  - contact.md

minima:
  date_format: "%d %B %Y"
  skin: solarized-dark
  social_links:
    linkedin: graham-garnsworthy
    github: ggarns-gh

permalink: /:title

show_excerpts: true

plugins:
  - jekyll-feed
