remote_theme: jekyll/minima

title: Ai Data Engineering
description: Adventures in Data Engineering will be a collection of articles about developing and maintaining data-oriented solutions.
author:
  name: Graham Garnsworthy

header_pages:
  - about.md

minima:
  skin: solarized-dark
  social_links:
    linkedin: graham-garnsworthy
    github: ggarns-gh

plugins:
  - jekyll-feed
